"""create telemetry table

Revision ID: f4916bab947f
Revises: 
Create Date: 2026-07-31 00:01:42.758022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4916bab947f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('telemetry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telemetry_id')
    )
    op.create_index(op.f('ix_telemetry_event_name'), 'telemetry', ['event_name'], unique=False)
    op.create_index(op.f('ix_telemetry_telemetry_id'), 'telemetry', ['telemetry_id'], unique=False)
    op.create_index(op.f('ix_telemetry_user_id'), 'telemetry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_user_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_telemetry_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_event_name'), table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
